### ISSUE TITLE
[HELP] Local Shibboleth installation?

### ISSUE THREAD

**Issue by Rambou** [drstearns/passport-uwshib#3]
I'm trying to create a service provider for my app to work with federated academic network here in Greece and i'm trying to make that work for a couple of days with no success.
So i would like to know if this implementation should have a local installation of the shibboleth software correctly configured to my server, to work. I mean do i need both nodejs passport-uwshib and shibboleth in the same server with the apache module for shibboleth to successfully be an SP?

Thanks in advance DR.

**Comment by drstearns** [comment]
Hi Rambou,

This library is specifically for the University of Washington's Shibboleth service. This is not a generic Shibboleth library. This library uses the [passport-saml](https://github.com/bergie/passport-saml) library, which is a generic Shibboleth library for Node. So you should be using passport-saml and not this library. This library simply presets various config properties for the UW Shibboleth service. Passport-saml does all the real work.

Passport-saml implements a Shibboleth SP, so you don't need Apache and you don't need the Apache shib module. I am running just a Node server with no Apache installed, and I'm able to redirect users to our IdP for authentication.

**Comment by Rambou** [comment]
Thanks for the answer Dr. It really helped me because my department also uses the same stack, so i was in need to get an idea of how you implemented for UW.

Thanks again. :blush: 

**P.S.**
Wish there were guys like you here to develop similar stuff that helps other people, but as it seems nobody cares anymore...

**Comment by drstearns** [comment]
No worries. Sorry for the late reply. I somehow turned off notifications so I didn't see this until recently.

All you need is passport-saml, but you might find my code useful for clues about how to configure passport-saml. You'll need your IdP's certificate, and your server's cert and private key. And you will probably need to register your server with the IdP (we have to do that here at UW).

Best of luck to you!
